// generated by lv2ttl2c from
// http://gareus.org/oss/lv2/fil4#mono

extern const LV2_Descriptor* lv2_descriptor(uint32_t index);
extern const LV2UI_Descriptor* lv2ui_descriptor(uint32_t index);

static const RtkLv2Description _plugin = {
	&lv2_descriptor,
	&lv2ui_descriptor
	, 0 // uint32_t dsp_descriptor_id
	, 0 // uint32_t gui_descriptor_id
	, "4 Band Parametric Filter" // const char *plugin_human_id
	, (const struct LV2Port[20])
	{
		{ "in", AUDIO_IN, nan},
		{ "out", AUDIO_OUT, nan},
		{ "filter", CONTROL_IN, 0.000000},
		{ "gain", CONTROL_IN, 0.000000},
		{ "sec1", CONTROL_IN, 0.000000},
		{ "freq1", CONTROL_IN, 200.000000},
		{ "q1", CONTROL_IN, 1.000000},
		{ "gain1", CONTROL_IN, 0.000000},
		{ "sec2", CONTROL_IN, 0.000000},
		{ "freq2", CONTROL_IN, 400.000000},
		{ "q2", CONTROL_IN, 1.000000},
		{ "gain2", CONTROL_IN, 0.000000},
		{ "sec3", CONTROL_IN, 0.000000},
		{ "freq3", CONTROL_IN, 1000.000000},
		{ "q3", CONTROL_IN, 1.000000},
		{ "gain3", CONTROL_IN, 0.000000},
		{ "sec4", CONTROL_IN, 0.000000},
		{ "freq4", CONTROL_IN, 10000.000000},
		{ "q4", CONTROL_IN, 1.000000},
		{ "gain4", CONTROL_IN, 0.000000},
	}
	, 20 // uint32_t nports_total
	, 1 // uint32_t nports_audio_in
	, 1 // uint32_t nports_audio_out
	, 0 // uint32_t nports_midi_in
	, 0 // uint32_t nports_midi_out
	, 0 // uint32_t nports_atom_in
	, 0 // uint32_t nports_atom_out
	, 18 // uint32_t nports_ctrl
	, 18 // uint32_t nports_ctrl_in
	, 0 // uint32_t nports_ctrl_out
	, 8192 // uint32_t min_atom_bufsiz
	, false // bool send_time_info
};
